server:
  port: 8080

spring:
  application:
    name: shiro_jwt_test
  redis:
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        # 最大空闲连接
        max-idle: 8
        # 最小空闲链接
        min-idle: 0
        # 最大连接数（负数表示没有限制）
        max-active: 8
        # 最大阻塞等待时间（负数表示没有限制）
        max-wait: 0
      # 链接超时时间（毫秒）
      timeout: 1000

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shiro_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.shiro.jwt.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: true
      logic-not-delete-value: false
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

logging:
  level:
    com.shiro.jwt.mapper: debug

mybatis:
  mapper-locations: classpath:/mapper/*.xml


